### ISSUE TITLE
API for per layer time (computation cost)

### ISSUE THREAD

**Issue by stevenwudi** [VeriSilicon/TIM-VX#113]
Does TIMVX has some exposed APIs to retrieve the computational cost information?

The usage scenario:

We have converted a HRNET and LiteHRNET  and run using Tengine+TIMVX.

| | HRNET | LiteHRNET |
| :---                                          | :-----: | :-----: |
| CPU|  1600ms | 400ms |
| NPU|33ms | 80ms |

We want to have a further diagnosis of which modules are actually the most time consuming ones.
Hence, I am writing to inquire the API for retrieving the computational cost (time-wise) if there is one in TIMVX.

**Comment by sunshinemyson** [comment]
We don't have perf API support yet.
