### ISSUE TITLE
Can I create multi Contexts and graphs?

### ISSUE THREAD

**Issue by janoslim** [VeriSilicon/TIM-VX#117]
Hello,

I am using TIM-VX for running multi NN, and I am using VIM3 board.
I'm referring to the sample code and I wonder what is the best solution for creating multiple nn in terms of performance?
I think about 
1) creating single Context multi graph,
2) creating multi graph and context each.

In addition, I want to run NN with layerwisely,
thus I tried creating multi graphs for each layer.
I wonder is there the limit for # of graphs ( and context)..
I want to create graphs like 100 or more because I want to check the hidden activations,
I wonder this possibly done with tim-vx.

Thank you!

**Comment by sunshinemyson** [comment]
Single Context with Multi Graph is prefered.
You can split the whole graph into multigraph with single layer, 100 graph is ok.

**Comment by janoslim** [comment]
Hi @sunshinemyson,
Thank you for your reply.
I just have one more question that
I wonder creating tim::vx::tensor for input and output(not transient) allocate memory for activation? it might be memory-heavy job  for embedded boatd to split layers.
