### ISSUE TITLE
Tensors connection between graphs

### ISSUE THREAD

**Issue by janoslim** [VeriSilicon/TIM-VX#118]
Hello!

I wonder I can connect two graphs and share Tensors between.

for example, 
Tensor1 -->  Graph1 -->  Tensor2 --> Graph2 -->  Tensor3

In this case, Tensor1 would be INPUT type, and Tensor3 would be OUTPUT type,
As I know, when running graph1 solely, Tensor2 would be OUTPUT type, and need to call CopyDatafromTensor(),
and call CopyDatatoTensor() to run graph2..

And I want to share Tensor2 without copying overhead.
Could I get some advice of this situation.

Additionally I wonder could i utilize TRANSIENT type and wonder what it is for.
Thank you for your favorable answers.

**Comment by sunshinemyson** [comment]
Hi Janoslim,

Share tensor between two graphs not supported yet. In the future, we will support share buffer between two graphs.
