### ISSUE TITLE
Does lenet sample works fine?

### ISSUE THREAD

**Issue by janoslim** [VeriSilicon/TIM-VX#12]
Hello,
I am trying to use tim-vx on vim3, and I build lenet example and run on vim3.
This just success to start program but fail on graph->Compile() that returns -1.
Does It works fine on other environment?
Thank you.

**Comment by thezha** [comment]
lenet example has been tested on vim3. Please make sure you use the supplied library files and kernel module from the prebuild-sdk rather than the sdk supplied on the vim3 board. If you continue to have trouble, please show your steps and logs. Thanks!

**Comment by janoslim** [comment]
Thank you for your reply.

**Comment by thezha** [comment]
A week old. Closing
