### ISSUE TITLE
Minimal tflite with vx-delegate example

### ISSUE THREAD

**Issue by bkovalenkocomp** [VeriSilicon/TIM-VX#123]
Hi, could you provide minimal example, for tflite inference with vx-delegate applied? 
Im not sure how to create and apply vx-delegate to tflite model. Thanks!

**Comment by sunshinemyson** [comment]
Yes, we are working on this. The demo will be avaible two weeks later.

**Comment by bkovalenkocomp** [comment]
> Yes, we are working on this. The demo will be avaible two weeks later.

looking forward for the example 👍

**Comment by rniranjan93** [comment]
I have a .tflite file , I want to build a graph with Delegate class and want to return the graph using the following method
`std::shared_ptr<tim::vx::Graph>& GetGraph() { return graph_; }`
could you provide an example from beginning, i.e, taking .tflite as input -> returning a builded tim::vx::Graph

**Comment by rniranjan93** [comment]
I have a .tflite file , I want to build a graph with Delegate class and want to return the graph using the following method
`std::shared_ptr<tim::vx::Graph>& GetGraph() { return graph_; }`
could you provide an example from beginning, i.e, taking .tflite as input -> returning a builded tim::vx::Graph

**Comment by sunshinemyson** [comment]
> 
> 
> I have a .tflite file , I want to build a graph with Delegate class and want to return the graph using the following method
> `std::shared_ptr<tim::vx::Graph>& GetGraph() { return graph_; }`
> could you provide an example from beginning, i.e, taking .tflite as input -> returning a builded tim::vx::Graph

Not understand your request fully, are you saying use tflite import the tflite file and get compiled vx graph object? Not a demo run tflite model with tflite+vx-delegate? Thanks

**Comment by rniranjan93** [comment]
> > I have a .tflite file , I want to build a graph with Delegate class and want to return the graph using the following method
> > `std::shared_ptr<tim::vx::Graph>& GetGraph() { return graph_; }`
> > could you provide an example from beginning, i.e, taking .tflite as input -> returning a builded tim::vx::Graph
> 
> Not understand your request fully, are you saying use tflite import the tflite file and get compiled vx graph object? Not a demo run tflite model with tflite+vx-delegate? Thanks

Yes

**Comment by sunshinemyson** [comment]
What's the purpose for this usage? It's quite strange to me if you want use tflite interpreter to extract model but don't want to inference it with tflite interpreter.

**Comment by rniranjan93** [comment]
Wanted to manipulate the graph

**Comment by sunshinemyson** [comment]
> 
> 
> Wanted to manipulate the graph

If you want ot manipulate the vx_graph, you have to hack the vx-delegate code. We can not have the vx-delegate graph object with tflite intepreter directly. What kinds of manipulation you want to try with vx_graph?

**Comment by rniranjan93** [comment]
No need for it now, thanks.
Could you provide minimal example, for tflite inference with vx-delegate applied?
Im not sure how to create and apply vx-delegate to tflite model. Thanks!

**Comment by sunshinemyson** [comment]
> 
> 
> No need for it now, thanks.
> Could you provide minimal example, for tflite inference with vx-delegate applied?
> Im not sure how to create and apply vx-delegate to tflite model. Thanks!

https://github.com/VeriSilicon/tflite-vx-delegate/pull/3 , I'll merge this PR soon. In this PR, I created demo for python/c++ with vx_delegate.

**Comment by bkovalenkocomp** [comment]
thanks for the help!
