### ISSUE TITLE
Is there a tool to convert pretrained NN model into executable binary？

### ISSUE THREAD

**Issue by Goose-Bomb** [VeriSilicon/TIM-VX#138]
I noticed that there is an example *lenet_lite* in which the NN graph is loaded from binary data  directly without building it from cpp code descriptions.

So how did the executable NN binary get generated? Is this feature part of OpenVX extensions? Where can I find the tool to convert pretrained NN models (e.g., in ONNX format) into executable binary that can be used by TIM-VX?

**Comment by thezha** [comment]
Network Binary Graph (NBG) is a proprietary format, and tools for converting a model directly to NBG is not openly distributed yet. However, you can generate NBG using TIM-VX CompileToBinary() API, as shown in this example (https://github.com/VeriSilicon/TIM-VX/blob/main/src/tim/vx/graph_test.cc).
