### ISSUE TITLE
Dequantization implementation for VSI_NN_OP_CAST Node?

### ISSUE THREAD

**Issue by Goose-Bomb** [VeriSilicon/TIM-VX#139]
Currently, When cast a **UINT8 |  VSI_NN_QNT_TYPE_AFFINE_ASYMMETRIC** tensor to **FLOAT32** tensor using VSI_NN_OP_CAST node, it can only do `output_value = (float32)input_value` instead of `output_value = (float32)(input_value - zero_point) * scale`.

I noticed that there is a `D_U8|Q_ASYM -> D_F32` op check in the `/src/tim/vx/internal/src/ops/vsi_nn_op_cast.c` source file, so why does this dequantization conversion is not available in the VSI_NN_OP_CAST Node?

**Comment by nightingalei** [comment]
@Goose-Bomb We suggest to use DataConvert(VSI_NN_OP_DATACONVERT) operation to implement quantize/dequantize operations.

https://github.com/VeriSilicon/TIM-VX/blob/47119a569dcdc1cae7720c126222c6c0991d1519/src/tim/vx/ops/simple_operations.cc#L39
