### ISSUE TITLE
Doesn't TIMVX support conv group=2?

### ISSUE THREAD

**Issue by clovking** [VeriSilicon/TIM-VX#144]
![image](https://user-images.githubusercontent.com/29460736/127131205-64f3a88c-c832-4d87-a704-1bff74c4bd68.png)
![image](https://user-images.githubusercontent.com/29460736/127131555-cd370465-2786-46bd-933f-ac42ab095ae1.png)

**Comment by sunshinemyson** [comment]
We have another dedicate GroupedConv2d operator for this case. Please use this one instead.

**Comment by clovking** [comment]
经测试 GroupedConv2d 算子，发现该接口存在 bug , pad 未传入
![image](https://user-images.githubusercontent.com/29460736/127444173-e07d4325-7bf7-497d-b163-ef2c5f2a2952.png)

**Comment by sunshinemyson** [comment]
Thanks for the PR. Already merged.

**Comment by clovking** [comment]
Great!!!
