### ISSUE TITLE
is tim-vx available to run graph with virtual tensors as i/o tensor?

### ISSUE THREAD

**Issue by janoslim** [VeriSilicon/TIM-VX#155]
Hello,

I am willing to modify tim-vx as the entire graph can be divided into subgraphs so that i can run the entire neural network seperated. The implementation of tim-vx shows that the input output tensor of the graph has a handle(memory allocated). According to my understanding of openVX, it seems that graph can have virtual tensor as input output, and I wonder if this is possible at the vsi_ level.

Thank you!

**Comment by sunshinemyson** [comment]
Hi janoslim,

Sorry， you can not set input/output as a virtual tensor in our implementation.

**Comment by janoslim** [comment]
Thank you for your help!
