### ISSUE TITLE
Is compilation method of tim-vx based on tvm?

### ISSUE THREAD

**Issue by janoslim** [VeriSilicon/TIM-VX#165]
Hello,

As I know, after calling graph->compile(),
tim-vx invoke vxVerifyGraph() and internally calling  compilation scheme,
And I wonder does the compilation method is based on tvm.

Thank you!!

**Comment by sunshinemyson** [comment]
No, we write our own compilation not based on tvm. However, we already support TVM as a backend.

**Comment by janoslim** [comment]
Thank You!
