### ISSUE TITLE
Does this software only support SOC for VeriSilicon's IP ?

### ISSUE THREAD

**Issue by benlvzi** [VeriSilicon/TIM-VX#168]
Does this software only support SOC for VeriSilicon's IP ?
Or can it run as long as it supports the openvx API, for example TI TDA4 soc

**Comment by sunshinemyson** [comment]
So far, it has only been verified with Verisilicon's NPU. We extended openvx a lot for AI

**Comment by benlvzi** [comment]
Thank you for your reply, i get it.
