### ISSUE TITLE
Programmablility of PPU in NPU of a311d(vim3)

### ISSUE THREAD

**Issue by janoslim** [VeriSilicon/TIM-VX#172]
Hello,
firstly, I'm always grateful for your kind answers.

As I know, vim3's npu contains PPU that programmable with openCL base, however I failed to find any usability of PPU in source code, and I wonder the PPU can be handled by openCL or other method. 

Thank you!

**Comment by sunshinemyson** [comment]
@janoslim ,

What do you mean "however I failed to find any usability of PPU in source code"? 

You can contact us by email "ML_Support@verisilicon.com" which may have better feedback in time.

Thanks

**Comment by janoslim** [comment]
okay Thanks a lot!
