### ISSUE TITLE
Could not access tensor attribute such as scale, zp  by tensor

### ISSUE THREAD

**Issue by lileiigithub** [VeriSilicon/TIM-VX#180]
In demo file: samples/lenet/lenet_asymu8.cc  add  line 315  to access scale of tensor [fc4_output]：
std::cout<< "fc4_output quantize:" << fc4_output->GetQuantization().Scales()[0] << std::endl;

Get error as follow  when compile:

/wksp/github/TIM-VX/samples/lenet/lenet_asymu8.cc:315:78: error: passing ‘const tim::vx::Quantization’ as ‘this’ argument discards qualifiers [-fpermissive]
  315 |   std::cout<< "fc4_output quantize:" << fc4_output->GetQuantization().Scales()[0] << std::endl;
      |                                                                              ^
In file included from /wksp/github/TIM-VX/include/tim/vx/operation.h:28,
                 from /wksp/github/TIM-VX/samples/lenet/lenet_asymu8.cc:33:
/wksp/github/TIM-VX/include/tim/vx/tensor.h:63:23: note:   in call to ‘std::vector<float>& tim::vx::Quantization::Scales()’
   63 |   std::vector<float>& Scales() { return this->scales_; }
      |                       ^~~~~~
make[2]: *** [samples/lenet/CMakeFiles/lenet.dir/build.make:63: samples/lenet/CMakeFiles/lenet.dir/lenet_asymu8.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:289: samples/lenet/CMakeFiles/lenet.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

**Comment by sunshinemyson** [comment]
We already have the fix. Please get latest code.
