### ISSUE TITLE
bazel compile Error 

### ISSUE THREAD

**Issue by yingshengBD** [VeriSilicon/TIM-VX#191]
<img width="1417" alt="图片" src="https://user-images.githubusercontent.com/74164525/137875603-065b3e15-70ad-430a-8543-159b420fdd1e.png">
i install bazel [lastest-version 4.2.1], and run "bazel build libtim-vx.so"

**Comment by thezha** [comment]
Try add the following to see if it fixes your problem. 

```
diff --git a/samples/lenet/BUILD b/samples/lenet/BUILD
index 46db564..507ed03 100644
--- a/samples/lenet/BUILD
+++ b/samples/lenet/BUILD
@@ -1,7 +1,7 @@
 cc_test(
     name = "lenet_asymu8_cc",
     copts = [
-        "-Werror", "-std=c++14"
+        "-Werror", "-std=c++14", "-pthread"
     ],
     srcs = [
         "lenet_asymu8.cc",
```
