### ISSUE TITLE
libOpenVX.so

### ISSUE THREAD

**Issue by stevenwudi** [VeriSilicon/TIM-VX#22]
When I make -j4 using tim-vx, I have encounter the following issue

`
Tengine/3rdparty/tim-vx/lib/x86_64/libOpenVX.so: file format not recognized; treating as linker script
`

Any idea how to solve it? Many thanks in advance for your answer.

**Comment by thezha** [comment]
This issue seems to be related to Tengine environment, I recommend that you raise the issue in the Tengine community to get better answers. 

https://github.com/OAID/Tengine/blob/tengine-lite/doc/npu_tim-vx_user_manual.md

**Comment by stevenwudi** [comment]
True, for tim-vx .so  files actually works for my A311D. I will close this issue.
