### ISSUE TITLE
TVM for VIM3L NPU Error

### ISSUE THREAD

**Issue by leokuo725** [VeriSilicon/TIM-VX#220]
While I compile model for VIM3L at TVM, I set environment variable VSIMULATOR_CONFIG=VIPNANOQI_PID0X99.
It shows "Warning: not found GPU configuration: VIPNANOQI_PID0X99, use default configuration: VIP7000".
I try to search "VIPNANOQI_PID0X99" in libEmulator.so. No VIPNANOQI_PID0X99 found.
What should I set for VSIMULATOR_CONFIG?

**Comment by sunshinemyson** [comment]
Hi Leoluo,

Can you try to build tvm compiler part on board too? If you compile model with board, you don't have to use this variable.

**Comment by sunshinemyson** [comment]
Close since inactive for over months.
