### ISSUE TITLE
supported tensor data types

### ISSUE THREAD

**Issue by xiangjunhuang** [VeriSilicon/TIM-VX#229]
Hi

In tim/vx/types.h, 

enum class DataType {
  UNKNOWN,
  INT8,
  UINT8,
  INT16,
  UINT16,
  INT32,
  UINT32,
  FLOAT16,
  FLOAT32,
  BOOL8
};

I don't see 64bit data types (int64, uint64, float64) included, which is not consistent with the descriptions in Programming_Guide.md as below:

> TIM-VX support the following data type:
> INT8
> INT16
> INT32
> INT64
> UINT8
> UINT16
> UINT32
> UINT64
> FLOAT16
> FLOAT32
> FLOAT64

Is there a reason of having this limitation? or it's a bug?

**Comment by antkillerfarm** [comment]
Sorry. It is a mistake in our document. We don't support 64bit data types now.
