### ISSUE TITLE
does aarch64_A311D_6.4.8.tgz support Linux Kernel 5.1x?

### ISSUE THREAD

**Issue by ideafold** [VeriSilicon/TIM-VX#241]
rt.
Thanks.

**Comment by ideafold** [comment]
uname -a:
Linux Khadas 5.16.0-rc2 #1.0.9 SMP Fri Dec 17 14:44:28 CST 2021 aarch64 aarch64 aarch64 GNU/Linux

aarch64_A311D_6.4.8 run with tengine lite failed.

gdb bt:
![微信图片_20211219123340](https://user-images.githubusercontent.com/1472973/146663999-3a20a053-7e41-4cdb-9002-707779e0cf50.jpg)

**Comment by sunshinemyson** [comment]
You can check dmesg if it compatible with your kernel or not when execute "insmod"

**Comment by ideafold** [comment]
aarch64_A311D_6.4.8/lib# insmod galcore.ko
insmod: ERROR: could not insert module galcore.ko: Invalid module format

dmesg said:
[  306.446813] galcore: version magic '4.9.y SMP preempt mod_unload modversions aarch64' should be '5.16.0-rc2 SMP mod_unload aarch64'



> You can check dmesg if it compatible with your kernel or not when execute "insmod"

aarch64_A311D_6.4.8/lib# insmod galcore.ko
insmod: ERROR: could not insert module galcore.ko: Invalid module format

[  306.446813] galcore: version magic '4.9.y SMP preempt mod_unload modversions aarch64' should be '5.16.0-rc2 SMP mod_unload aarch64'

**Comment by ideafold** [comment]
it looks like the aarch64_A311D_6.4.8 is compiled in kernel 4.9. Would you be kind of to compile one use 5.16 kernel?

or tell me the method to compile.

Thanks.

**Comment by sunshinemyson** [comment]
@ideafold ,

No plan to do this yet. Please stay with kernel 4.9, kernel module required commercial license, so you cannot compile it by yourself.

**Comment by sunshinemyson** [comment]
@ideafold ,

You can ask Khadas for the kernel driver build with 5.16 kernel. They should support this as vendor. Thanks
