### ISSUE TITLE
tim vx  x86_64_linux simulation uint8 model run very slow

### ISSUE THREAD

**Issue by ideafold** [VeriSilicon/TIM-VX#245]
x86 simulator:
889999 inference used_time 33216.33 ms

A311D
889999 inference used_time 559.47 ms

x86模拟运行，这么慢，正常吗？

**Comment by sunshinemyson** [comment]
@ideafold , 模拟运行慢是正常的，因为要做一些比较lowlevel的运算行为的模拟。

**Comment by ideafold** [comment]
收到。谢谢
