### ISSUE TITLE
libOpenVX.so version problem

### ISSUE THREAD

**Issue by ywangwxd** [VeriSilicon/TIM-VX#247]
I am using Rockcip rv1126, builtroot system. I can find libOpenVX.so.1.2 on the board. But the version depended in this git repo is libOpenVX.so.1.3.0. I can find this in the prebuilt directory and only x86 version is provided. How should I make it work on libOpenVX.so.1.2?

**Comment by minggang-vsi** [comment]
can you use amlogic vim3(A311D) board?  Verisilicon can support vim3 board directly.

https://www.khadas.cn/vim3

**Comment by sunshinemyson** [comment]
@ywangwxd  Are you still have trouble with this?
