### ISSUE TITLE
Can not find operation_private.h in the project.

### ISSUE THREAD

**Issue by TangYuan-Liu** [VeriSilicon/TIM-VX#252]
I got error when compiliing:
![image](https://user-images.githubusercontent.com/29272811/147636917-fdbd45eb-9a42-48e5-8e08-46d3e4273fcf.png)

Please double check this pull request: https://github.com/VeriSilicon/TIM-VX/pull/250

**Comment by liyuenan2333** [comment]
this error has been fixed, thank you for reminding.
