### ISSUE TITLE
 cpu_backend/npuref_interface.h: No such file or directory

### ISSUE THREAD

**Issue by wlt027** [VeriSilicon/TIM-VX#268]
Hi,I have a problem when building tim-vx in Tengine on VIM3 pro, my  system is ubuntu18.04 xface by the way

 cpu_backend/npuref_interface.h: No such file or directory

how can i get this file?

**Comment by sunshinemyson** [comment]
@wlt027 ,

This file should not required. Could you share how did you build Tim-vx? we have release new driver sdk for vim3 https://github.com/VeriSilicon/TIM-VX/releases/tag/v1.1.37

**Comment by gdh1995** [comment]
I also met this. I was compiling Tengine (https://github.com/OAID/Tengine/blob/tengine-lite/doc/docs_zh/source_compile/compile_timvx.md), and:
* `Tengine` commit is https://github.com/OAID/Tengine/commit/1aea916c9cb566393c243c4cc6b4e64fb563dd93
* `TIM-VX` is in fe91e7f (2022-01-12 14:39, Update README.md)
* files in `TIM-VX` which need this file are:
  * `src/tim/vx/internal/src/kernel/cpu/cpu_backend_conv2d_cpu.c`
  * `src/tim/vx/internal/src/kernel/cpu/cpu_backend_deconv2d_cpu.c`
  * `src/tim/vx/internal/src/kernel/cpu/depthwise_conv1d_cpu.c`

Tengine has suggested users should use commit 68b5acb of TIM-VX in https://github.com/OAID/Tengine/commit/00f31fcce72f328c44fc9a831a8e6b0e6d4d1f42

**Comment by wlt027** [comment]
> I also met this. I was compiling Tengine (https://github.com/OAID/Tengine/blob/tengine-lite/doc/docs_zh/source_compile/compile_timvx.md), and:
> 
>     * `Tengine` commit is [OAID/Tengine@1aea916](https://github.com/OAID/Tengine/commit/1aea916c9cb566393c243c4cc6b4e64fb563dd93)
> 
>     * `TIM-VX` is in [fe91e7f](https://github.com/VeriSilicon/TIM-VX/commit/fe91e7f13d351e2c319f0b476c1c600ed323d738) (2022-01-12 14:39, Update README.md)
> 
>     * files in `TIM-VX` which need this file are:
>       
>       * `src/tim/vx/internal/src/kernel/cpu/cpu_backend_conv2d_cpu.c`
>       * `src/tim/vx/internal/src/kernel/cpu/cpu_backend_deconv2d_cpu.c`
>       * `src/tim/vx/internal/src/kernel/cpu/depthwise_conv1d_cpu.c`
> 
> 
> Tengine has suggested users should use commit [68b5acb](https://github.com/VeriSilicon/TIM-VX/commit/68b5acbe7c90bceae073d4bfca60ffa92dff0fc4) of TIM-VX in [OAID/Tengine@00f31fc](https://github.com/OAID/Tengine/commit/00f31fcce72f328c44fc9a831a8e6b0e6d4d1f42) .
> 
> **Update:** the commit [68b5acb](https://github.com/VeriSilicon/TIM-VX/commit/68b5acbe7c90bceae073d4bfca60ffa92dff0fc4) does work.

thank you,problem solved
