### ISSUE TITLE
Whether include pad pixels when calculating AveragePool values for the edges

### ISSUE THREAD

**Issue by wdian** [VeriSilicon/TIM-VX#272]
When I was calculating averagePool, I noticed that the pad value sometimes computed, sometimes not computed.

![average_pool_1](https://user-images.githubusercontent.com/33274596/149704139-50eb394d-46e9-49ab-bee3-735ca06fc123.png)

As shown above, the result is 19 if the pad value is not computed, and 6.84 if the pad value is computed.

**Comment by sunshinemyson** [comment]
Thanks for your feedback. 

What do you mean "sometimes"? Are you saying this is a random issue?

**Comment by wdian** [comment]
Not random, I tested two models， The following two models, the first one calculates the pad value, the other does not.

<img width="500" alt="average_pool_m0" src="https://user-images.githubusercontent.com/33274596/149713593-7d9225b6-6a6e-42aa-a50a-f6913c439b7d.PNG">
<img width="500" alt="average_pool_m1" src="https://user-images.githubusercontent.com/33274596/149713620-c8a09cfc-03ba-4830-aa96-324191d48414.PNG">

**Comment by wdian** [comment]
Is this problem solved?

**Comment by wdian** [comment]
averagepool only supported ceil_mode=1 for onnx,  the default parameters ceil_mode=0  do not support.
