### ISSUE TITLE
Is the `pad_` parameter missing from the groupedconv1d constructor？

### ISSUE THREAD

**Issue by MESeraph** [VeriSilicon/TIM-VX#284]
I didn't find that the member variable `pad_` was used in https://github.com/VeriSilicon/TIM-VX/blob/main/include/tim/vx/ops/groupedconv1d.h.
This class cannot override `pad_` to be used situation.

**Comment by sunshinemyson** [comment]
@MESeraph ,

Thanks for your feedback, I'll ask team fix this.

**Comment by MESeraph** [comment]
@sunshinemyson I don't understand what you mean. I want to use groupedconv1d with pad parameter, not conv1d.

**Comment by sunshinemyson** [comment]
@MESeraph  sorry, I messed it up. I'll double check.
