### ISSUE TITLE
Compiled network caching

### ISSUE THREAD

**Issue by bkovalenkocomp** [VeriSilicon/TIM-VX#287]
Hi I have a question ;-)

As far as I understand, currently, during model initialisation there is conversion / compiling step. Model from tensroflow lite is converted into TIM-VX representation. It happens every time and for big models can take as long as 5 min. 
We don't have problem with this (at least for now). But I think a caching mechanism can greatly speedup initialisation time. Model in TIM-VX representation can be dumped on disk and loaded during initialisation. 

Do you have a caching mechanism on your roadmap? I think it's very important / needed feature for many use cases.
Thanks.

**Comment by sunshinemyson** [comment]
Hi bkovalenkocomp,

Yes, we already implement similar feature in tflite-vx-delegate. Please check it:

https://github.com/VeriSilicon/tflite-vx-delegate/commit/c862e75266bcccae1fdd2d6b91c9017c5d04a918
