### ISSUE TITLE
Test graph.gen_binary_graph_with_simple_add failing on i.MX8 MPlus

### ISSUE THREAD

**Issue by robert-kalmar** [VeriSilicon/TIM-VX#289]
Unit test `graph.gen_binary_graph_with_simple_add` fails with Segmetation fault on i.MX8 MPlus platform:
```
# ./unit_test --gtest_filter="graph.gen_binary_graph_with_simple_add"               
Running main() from /home/nxf39574/2019_AITEC/REPOS/tim-vx/build/_deps/googletest-src/googletest/src/gtest_main.cc
Note: Google Test filter = graph.gen_binary_graph_with_simple_add
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from graph
[ RUN      ] graph.gen_binary_graph_with_simple_add
Segmentation fault
```

Build Configuration: 

- revision: 7c63ba621ec9718476e0e3292b6545e838eb0221
- CONFIG = YOCTO
- TIM_VX_USE_EXTERNAL_OVXLIB = ON (OVXLIB version 1.1.34)
- Driver: 6.4.3.p4

**Comment by sunshinemyson** [comment]
@robert-kalmar ,

This is identified as a low-level driver issue. We will fix it ASAP. Thanks
