### ISSUE TITLE
About parameter "step" for Slice 

### ISSUE THREAD

**Issue by ahqzy** [VeriSilicon/TIM-VX#308]
Hi,
    When using operator Slice, we can't config parameter step(it's 1 default),  do you have a plan to fix it?

**Comment by sunshinemyson** [comment]
Thanks for feedback. Marked as feature request will be investigated and implemented.

**Comment by sunshinemyson** [comment]
e8ca6b8ee376b6f201f257e9e8ed0d6d1d721a93
