### ISSUE TITLE
How can I get the intermediate output of a model?

### ISSUE THREAD

**Issue by ahqzy** [VeriSilicon/TIM-VX#309]
Hi 
    I'm debuging some onnx model, I want to compare the result between cpu and gpu., so I need get all intermediate output. I can get them when in cpu mode like this article: https://blog.csdn.net/Artyze/article/details/116270215.
    But In the gpu mode, I only get the last reslut, can't get any intermediate output. why?

**Comment by sunshinemyson** [comment]
@ahqzy ,

We don't provide this capability from TIM-VX level. I suggest you can implement this feature from ONNXRT side by:

If debugging per layer dump enabled:
    create Tim-vx tensor with attribute = OUTPUT instead of TRANSIENT

Then you can dump tensor with CopyDataFromTensor()

**Comment by ahqzy** [comment]
@sunshinemyson  Sorry, maybe I didn't express my requirement clearly. For exampe, I have a model as below:

![onnx](https://user-images.githubusercontent.com/53818187/156280375-fb505668-88a6-4093-854a-d26acfb17c3c.png)

How can I get all intermediate node(MaxPool、Conv...... Relu) output when the model has been completed？

**Comment by sunshinemyson** [comment]
How did you create tensor for those intermediate nodes? what kinds of attribute?

Only tensor with In/output as its attribute can be read. You need to change the model construction code.

**Comment by xuke537** [comment]
@ahqzy  You can append the intermediate outputs to the onnx graph outputs to check the results.
eg.
import onnx
from onnx import helper
model = onnx.load('xx.onnx')

intermediate_tensor_name = 'xxx'
model_path = 'xx_new.onnx'
intermediate_layer_value_info = helper.ValueInfoProto()
intermediate_layer_value_info.name = intermediate_tensor_name
model.graph.output.append(intermediate_layer_value_info)
onnx.save(model, model_path)

**Comment by ahqzy** [comment]
@xuke537  Using that method, I can get  intermediate output for some models. But I can't get  intermediate output for another models(such as above picture).  I guess the reason is that VSI optimize some operator(for exampe, conv+bn)，so we can't get the intermediate output for conv. Do you have idea about it(or is there any method to disable the optimize for debug)?

**Comment by xuke537** [comment]
For debug， you can cut your model.
