### ISSUE TITLE
The compilation error: variable-sized object may not be initialized

### ISSUE THREAD

**Issue by hong19860320** [VeriSilicon/TIM-VX#324]
When I compile this library with android-ndk-r20b for android armeabi-v7a, the following error occurs:

`
tim-vx/src/tim/vx/ops/custom_base.cc:165:44: error: variable-sized object may not be initialized
    vsi_nn_kernel_node_param_t node_params[param_num] = {NULL};
` 

So I found the following solution:

`
    vsi_nn_kernel_node_param_t node_params[param_num];
    memset(node_params, 0, sizeof(vsi_nn_kernel_node_param_t) * param_num);
`

**Comment by sunshinemyson** [comment]
@hong19860320 ,

Thanks for your feedback. I think it because clang have different warning rule compare to GCC. We will check if we can replace it with memset or not - maybe can do it in another approach.

Thanks

**Comment by sunshinemyson** [comment]
Fixed by 08500158ba96ce1a6f0f4e2ac6fc289fca4f3c11
