### ISSUE TITLE
android for arm 32 bit

### ISSUE THREAD

**Issue by watchyou** [VeriSilicon/TIM-VX#33]
Do you have any plans to support Android (arm 32 bit)

**Comment by thezha** [comment]
We target for Android support by end of May 2021. Thanks!

**Comment by stevenwudi** [comment]
Yes, we the support of Android (arm 32 bit) will be quite essential for our team project.
Looking forward to the release

**Comment by thezha** [comment]
Please let us know the exact Android SDK you are using? Is it from official VIM3? https://docs.khadas.com/vim3/DownloadAndroidSourceCode.html

**Comment by stevenwudi** [comment]
We customised our android system based on Android 10. It is not from Khadas provided system.
Does the Android SDK matters in terms of TIMVX integration?

**Comment by thezha** [comment]
Android SDK itself doesn't matter that much, but we need to know the kernel driver version.

**Comment by stevenwudi** [comment]
Our kernel version is 4.9
Looking forward to hearing back any progress :)

**Comment by stevenwudi** [comment]
My wechat ID is: stevenwudibbb
If it's ever needed for expedite the process of anything unclear.
Best regards

**Comment by stevenwudi** [comment]
I am wondering if there is a certain release date for the support of Android system(arm 32 bit). Our team leader is actively thinking about alternatives for VSI  from Amlogic(which of course I personally didn't want another NPU provider given our team has spent quite some effort in using TIMVX for project development).
Really looking forward to the support of android 32 bit asap...

**Comment by thezha** [comment]
Resolved with [SHA03a53](https://github.com/VeriSilicon/TIM-VX/commit/03a53cba7e90948b4b1cb59634d9f871d545d625)

mkdir build; cd build
cmake -DCMAKE_TOOLCHAIN_FILE=android-ndk-r21e/build/cmake/android.toolchain.cmake ..
make
