### ISSUE TITLE
TVM supported？

### ISSUE THREAD

**Issue by 2050airobert** [VeriSilicon/TIM-VX#343]
Hi，
     If Vivante NPU like a311d is  supported by TVM？ Yet I could not see any document about that？
     So is there any web link about how to use NPU cooperated with TVM？Tks

BR

**Comment by 2050airobert** [comment]
Hi，any one could support？

**Comment by sunshinemyson** [comment]
@2050airobert ,

https://github.com/VeriSilicon/tvm/blob/vsi_npu/README.VSI.md Please check this guide. Thanks.
