### ISSUE TITLE
[Lite HRNet] op supported - Conditional Channel Weighting ，Spatial Weight Computation and Cross-Resolution Weight 

### ISSUE THREAD

**Issue by 2050airobert** [VeriSilicon/TIM-VX#353]
Hi，
Could TIM-VX support Conditional Channel Weighting ，Spatial Weight Computation and Cross-Resolution Weight Computation layer computation already？
If not ，how to implement thest by ourselves？

BR

**Comment by sunshinemyson** [comment]
@2050airobert ,

Thanks for feedback. Do you have more detail about those operation? Thanks

**Comment by sunshinemyson** [comment]
@2050airobert ,

I checked the building blocks defined by llitehrnet.py in https://github.com/HRNet/Lite-HRNet.git.

My idea is those three blocks reused 1x1 conv and depthwise conv as cornerstone. It should be supported already.

Thanks
