### ISSUE TITLE
Why is  the shape/dimensions parameter  date type of Broadcast OP  int32_t ?

### ISSUE THREAD

**Issue by MESeraph** [VeriSilicon/TIM-VX#376]
<img width="874" alt="Screen Shot 2022-04-25 at 2 10 40 PM" src="https://user-images.githubusercontent.com/56160181/165240484-87e16fc6-d7e7-4bcd-bc57-476a982e2de2.png">
The shape/dimensions parameter  data type of Boardcast is `int32_t`.
It will be convert to `uint32_t` by Boardcat contruct function.
Why not set parameter to `uint32_t` type?

**Comment by chxin66** [comment]
done
