### ISSUE TITLE
vsi_nn_op_gather_elements.c inputs num error

### ISSUE THREAD

**Issue by MESeraph** [VeriSilicon/TIM-VX#382]
https://github.com/VeriSilicon/TIM-VX/blob/main/src/tim/vx/internal/src/ops/vsi_nn_op_gather_elements.c

```c
#define _INPUT_NUM   (2)
```

**Comment by sunshinemyson** [comment]
@MESeraph ，

Thanks for your feedback. I'll ask developer check it.

**Comment by sunshinemyson** [comment]
We have fixed this issue.
