### ISSUE TITLE
Support MaxPoolWithArgmax in general

### ISSUE THREAD

**Issue by HarwardDing** [VeriSilicon/TIM-VX#394]
目前使用 MaxpoolWithArgmax 去進行 compose OP,
當設定 ksize 與 stride 數字不同時，compile 會失败，
![image](https://user-images.githubusercontent.com/105416951/168020656-e1008a06-687f-42e4-aa92-c65b343a6356.png)

![image](https://user-images.githubusercontent.com/105416951/168025891-fde22d46-bb47-4e98-9482-d85479379dc3.png)

理論上這兩個參數的設定不用綁定相同的值，請幫忙了解有問題的地方，謝謝

**Comment by sunshinemyson** [comment]
@HarwardDing din，

我们尝试了在shape_3_3_1_fp32_kernel_2_stride_2这个测试用例的基础上将stride修改成1,1， 但是无法复制你说的问题。如果你还是有困惑，可以提一个PR包含的用例，我们走一下CI。

**Comment by sunshinemyson** [comment]
Tracked by internal task list.

**Comment by sunshinemyson** [comment]
Done
