### ISSUE TITLE
RNNCell 

### ISSUE THREAD

**Issue by MESeraph** [VeriSilicon/TIM-VX#410]
ActivationType is kSIGMOID in [RNNCell_UT](https://github.com/VeriSilicon/TIM-VX/blob/main/src/tim/vx/ops/rnn_cell_test.cc),
but kTanh is only supported in [RNNCell](https://github.com/VeriSilicon/TIM-VX/blob/main/src/tim/vx/ops/rnn_cell.cc) code.
Will RNNCell be completely refactored？

**Comment by sunshinemyson** [comment]
Hi MESeraph,

If you have proper use-case, I think you can add support for other activation.

Thanks

**Comment by MESeraph** [comment]
@sunshinemyson OK
