### ISSUE TITLE
How should Ovxlib contribute?

### ISSUE THREAD

**Issue by MESeraph** [VeriSilicon/TIM-VX#411]
Hello，
When I was modifying RNN, I found some problems with Ovxlib.
Can I submit the modification of Ovxlib?

**Comment by sunshinemyson** [comment]
@MESeraph , 

Yes, you can do this. 
Appreciate that you want contribute this. Since OVXLIB we have internal process on it. We need to forward your patch internally and then publish it once pass internal check.

Please be aware that your commit information will be erased out in this case.

Thanks

**Comment by MESeraph** [comment]
@sunshinemyson I got. Thank you!
