### ISSUE TITLE
RNN/LSTM/GRU Planned 

### ISSUE THREAD

**Issue by MESeraph** [VeriSilicon/TIM-VX#415]
Whether the following operators can be completed normally in 22Q3.
Is there a plan to achieve **BidirectionalSequenceGRU**？
<img width="1021" alt="Screen Shot 2022-06-21 at 6 38 21 PM" src="https://user-images.githubusercontent.com/56160181/174780689-c6fc2646-bfd9-48c5-bfe7-78bf5337528e.png">
It may affect my project progress.
I look forward to your reply,  thank you!

**Comment by sunshinemyson** [comment]
Hi MESeraph,

BidirectionalSequenceGRU is not in our radar. Other operation can be supported.

**Comment by MESeraph** [comment]
I got. Thank you!
