### ISSUE TITLE
Grouped Conv2D optimization when groups equal to input channels

### ISSUE THREAD

**Issue by fengwang** [VeriSilicon/TIM-VX#420]
When the input channels and groups are identical, which is a common case of networks, the GroupedConv2d is basically Depthwise Conv2D of depth 1. 

Given the fact that stacked Conv2D for GroupedConv2d is not efficient (https://github.com/VeriSilicon/TIM-VX/blob/3e8d5e3493cc8bbd6908b72d2b7fe2d508a397c4/src/tim/vx/internal/src/ops/vsi_nn_op_grouped_conv2d.c#L148) when the number of groups is large (32, 64, 128 etc ), maybe it is a good idea optimize Grouped Conv2D into Depthwise Conv2D when the input channels are equal to the groups?

**Comment by sunshinemyson** [comment]
Hi FengWang,

In such case input_channel equal to group number. You should map it to depthwise conv directly.
