### ISSUE TITLE
"*.tflite" to "*.tmfile" conversion issue.

### ISSUE THREAD

**Issue by kprastey** [VeriSilicon/TIM-VX#427]
Need to run custom mobilenetV2 based "*.tflite" model on the Khadas-VIM3's NPU.

Tried converting a custom mobilenetV2 based classifier model from "*.tflite" to "*.tmfile", but faced the following error.

![image_1](https://user-images.githubusercontent.com/46772194/177522587-b55a9ff6-89a2-4b19-a103-31a60235973d.png)

It seems like one of the operations (i.e. DEQUANTIZE) isn't supported.

also tried "*.tflite" -> "*.onnx" ->"*.tmfile". which gave similar errors.

![image_2](https://user-images.githubusercontent.com/46772194/177523427-979fb041-5f6b-45e1-9b3c-f239be5cfc8b.png)

Looking forward to having technical assistance from your end regarding running custom "*.tflite" models having operations like DEQUANTIZE, QUANTIZE, etc. on the khadas VIM3's NPU.

**Comment by sunshinemyson** [comment]
Sorry, We don't have knowledge about this tool. We can support tflite model directly with tensorflowlite + vx-delegate, you can try this approach.

**Comment by kprastey** [comment]
Hey @sunshinemyson,

- It'll be great if you could guide with some documented steps or provide any reference material to help use "tensorflowlite + vx-delegate", especially on the Khadas VIM-3 platform.
- If that's not possible then any platform-agnostic references would also be appreciated.

**Comment by sunshinemyson** [comment]
@kprastey ,

https://github.com/VeriSilicon/tflite-vx-delegate Can you to work out by follow the README.md firstly?
