### ISSUE TITLE
Useless TVM with a311d NPU?

### ISSUE THREAD

**Issue by 2050airobert** [VeriSilicon/TIM-VX#431]
hello， 
    1  Is there any example about how to using  TVM with TIM-VX  a311d NPU？
    2 Could the link  “https://github.com/VeriSilicon/tvm” accelerate the speed of executing the TIM-VX model or anything usefull with a311d NPU？
    3  Is there any example to show the power or usefullness of the  VeriSilicon/tvm project with a311d NPU ?

BR

**Comment by sunshinemyson** [comment]
@2050airobert ,

Looks like your work is heavily related with A311D platform, you can reach us by email. We can discuss more then.

Thanks
