### ISSUE TITLE
Imporved as RKNN supporting PT model to timvx?

### ISSUE THREAD

**Issue by 2050airobert** [VeriSilicon/TIM-VX#433]
hi,
    1 As we see, there is some framework or tools  that could transform the pytroch model to NPU model  just like RKNN.
    Could we or anyone else could support the tools or code to complete this converting? 
    2  Quantinatization is a boring work, yet qat  is so usefull for us when working on the a311d NPU. So is there any method to directly support the pytorch QAT (quantization aware training) ？ 
    3 Have we got the statistics data with all the cnn framework available on the a311d NPU,which one is the efficientest？ And how fast are they ， and what is  the best utilization ratioof information of them？
    4 Could we support the arbitrary subgraph spliting？ Which one should we choose for graph spliting and layer/graph level accelerating ?
BR 

BR

**Comment by sunshinemyson** [comment]
Hi @2050airobert ,

1. We have acuitylite which can downloaded from PIP install. You can try it out.
2. We are working on this, will share more information once we have.
3. We don't evaluate framework efficiency, you can contact us and share more information about this.
4. Graph partition usually is the frontend's job, not for TIM-VX which is a backend.

Thanks for feedback. Let me know if have follow-up questions.
