### ISSUE TITLE
Import question about tvm_vsi version!!!

### ISSUE THREAD

**Issue by 2050airobert** [VeriSilicon/TIM-VX#436]
Hi, 
    1 Does  tvm vsi_npu version support int8 full quant on the a311d NPU?
    2 I mean  input is just  an onnx model, and then could we covert it with TVM , finally put the result model onto the a311d NPU.
    3 Perlay or perchannnel quant supported now ? If not ,when it can ,tks !
    4 Is there any detailed document or weblink  about how to run the cnn model with the TVM vsi_npu？
BR

**Comment by sunshinemyson** [comment]
1. int8 full quantize can be support.
2. Not understand
3. depends on hw version. It can support in latest design.
4. https://github.com/VeriSilicon/tvm/tree/vsi_npu/tests/python/contrib/test_vsi_npu
