### ISSUE TITLE
x86 prebuilt sdk debug issue

### ISSUE THREAD

**Issue by 0b11101010** [VeriSilicon/TIM-VX#464]
Hello,

I'm developing a software using tim-vx prebuilt x86 sdk on my Ubuntu machine. I want to debug the software, but I see an error when the debug session starts, it says "Unable to connect to server!". Is it intentionally made to block debugging? Can you make suggestion if it is not? 

Best regards,
Erhan.

**Comment by sunshinemyson** [comment]
@0b11101010 ，

Please set env "DISABLE_IDE_DEBUG=1" before you use gdb.

**Comment by 0b11101010** [comment]
Thanks.
