### ISSUE TITLE
About tim-vx cross correlation support

### ISSUE THREAD

**Issue by 0b11101010** [VeriSilicon/TIM-VX#467]
Hello,
![model onnx](https://user-images.githubusercontent.com/48746516/186404024-e7a33ab7-31b1-4421-9aa9-3eb592ec3d36.png)

As show in the figure, I have a basic cross correlation model. 'x_f' and 'z_f' are inputs. It is actually a 2D convolution operation, but kernel weights come as input, here z_f is a kernel. As I understand, in tim-vx weight tensors must be frozen. Is there a way to make this model work on NPU? Should I implement a custom op containing OpenCL kernel? I thought also that, since the model is very simple, runtime graph compilation may work. What do you suggest?

Best regards,
Erhan.

**Comment by sunshinemyson** [comment]
@0b11101010 ,

NPU can support your model with its PPU inside. The performance is not good as frozen weights case.

Thanks
