### ISSUE TITLE
deconv group parameter

### ISSUE THREAD

**Issue by stevenwudi** [VeriSilicon/TIM-VX#50]
Could TIMVX update the "deconv" ops with a "group" parameter so that it could match the Tengine deconv configuration?

Looking forward to your answer. 

Best

**Comment by sunshinemyson** [comment]
https://github.com/VeriSilicon/TIM-VX/pull/51
We only support group = in_channel_count, in another word, only depthwise case. 

Please try this patch on your board, and you may need driver stack update from the chip vendor.
