### ISSUE TITLE
YOLOv8-s model, Eltwise ADD compute wrong in shape [2,8400,1]

### ISSUE THREAD

**Issue by yingshengBD** [VeriSilicon/TIM-VX#554]
硬件环境：瑞芯微rv1126，Galcore版本：6.4.6.5，也不能更新了 这是他们最新的驱动了 也不会再更新
背景：这是一个yolov8-s的开源模型，在模型neck部分存在如下Eltwise ADD layer，维度较大
![image](https://user-images.githubusercontent.com/74164525/218035348-4d28e547-de60-4142-80e9-302535aa49aa.png)

目前我们发现仅这一个算子就有明显的计算错误，怀疑是维度超出芯原的某些限制。
在此我基于TIM-VX op UT的elementwise_test.cc 中的TEST(Div, Div_uint8)，修改了一版 ADD uint8的UT，麻烦芯原大佬们看看，
简单说明这个UT：首先是输入维度和value，x和y矩阵都是一样的shape [2, 8400, 1]，x为全10，y为全5，scale都为1.0f，zp为128
![image](https://user-images.githubusercontent.com/74164525/218036487-e167d526-e378-438d-b676-ab1a18e4ae7a.png)
关于输出校验正确性的golden-data，我不确定TIM-VX的CopyDataFromTensor会不会有反量化的操作，所以姑且写为 10+5，
![image](https://user-images.githubusercontent.com/74164525/218037356-b40d2551-b610-46d4-9e5a-e8799126b8a5.png)
如果跟我想的不一样，还麻烦芯原大佬们调整golden-data

如下是代码，直接复制黏贴应该就能用：
TEST(Add, Add_uint8_yolov8) {
  auto context = tim::vx::Context::Create();
  auto graph = context->CreateGraph();

  tim::vx::ShapeType input_shape({2, 8400, 1});
  tim::vx::Quantization input_quant(tim::vx::QuantType::ASYMMETRIC, 1.0, 128);
  tim::vx::TensorSpec input_spec(tim::vx::DataType::UINT8, input_shape,
                                 tim::vx::TensorAttribute::INPUT, input_quant);
  // init the input, the shape is same, no need to broadcast
  // data1 is all 10, shape[2, 8400, 1]
  // data2 is all 5, shape[2, 8400, 1]
  // set the input_quant_info as: scale=1, zp=128
  // set the output_quant_info as: scale=1, zp=128
  uint8_t data1[2 * 8400];
  memset(data1, 10, 2 * 8400 * sizeof(uint8_t));
  uint8_t data2[2 * 8400];
  memset(data2, 5, 2 * 8400 * sizeof(uint8_t));
  auto input1 = graph->CreateTensor(input_spec, data1);
  auto input2 = graph->CreateTensor(input_spec, data2);

  tim::vx::ShapeType output_shape({2, 8400, 1});
  tim::vx::Quantization output_quant(tim::vx::QuantType::ASYMMETRIC, 1.0, 128);
  tim::vx::TensorSpec output_spec(tim::vx::DataType::UINT8, output_shape,
                                  tim::vx::TensorAttribute::OUTPUT,
                                  output_quant);
  auto output = graph->CreateTensor(output_spec);

  auto op = graph->CreateOperation<tim::vx::ops::Add>();
  (*op).BindInputs({input1, input2}).BindOutputs({output});

  if (!graph->Compile()) {
    std::cout << "Compile graph fail." << std::endl;
    EXPECT_TRUE(-1);
  }

  graph->PrintGraph();

  if (!graph->Run()) {
    std::cout << "Run graph fail." << std::endl;
    EXPECT_TRUE(-1);
  }

  std::vector<uint8_t> output_data;
  // the golden-output should be all 10+5
  std::vector<uint8_t> golden(2 * 8400, 10+5);
  output_data.resize(2 * 8400);
  if (!output->CopyDataFromTensor(output_data.data())) {
    std::cout << "Copy output data fail." << std::endl;
    EXPECT_TRUE(-1);
  }

  EXPECT_TRUE(ArraysMatch(golden, output_data, (uint8_t)1));
}

**Comment by chenfeiyue-cfy** [comment]
Hi,the answer is correct because the output value is underflow. It is blame to the quantization parameters set. If input and output have the same quantization params, the output of element-wise op such as add maybe have a math overflow or underflow.
