### ISSUE TITLE
how can i get the vx_lite.h when build with rv1126 sdk

### ISSUE THREAD

**Issue by zjd1988** [VeriSilicon/TIM-VX#627]
In order to run bianry model file, I need to compile TIM-VX with -DTIM_VX_ENABLE_VIPLITE=ON, but get error
```
xxxxx/src/tim/lite/handle_private.h: fatal error: vip_lite.h: No such file or directory
   30 | #include "vip_lite.h"
```
I have find https://github.com/YuzukiHD/Yuzukilizard/blob/master/Software/BSP/openwrt/package/npu/viplite-driver/include/vip_lite.h, how to confirm if the version is consistent with rv1126 sdk.

**Comment by sunshinemyson** [comment]
@zjd1988 ,

You need to contact SoC vendor for LiteDriver binaries.
