### ISSUE TITLE
请问这一套是否能搭建在rockchip的板子上呢？

### ISSUE THREAD

**Issue by yingshengBD** [VeriSilicon/TIM-VX#64]
比如rk1808或者rv1109

**Comment by thezha** [comment]
It is possible, you just need to compile TIM-VX against the prebuilt libraries provided by these platforms.

**Comment by kalcohol** [comment]
@yingshengBD Tengine 文档已经更新了 RK 的支持，请见：
https://github.com/OAID/Tengine/blob/tengine-lite/doc/npu_tim-vx_user_manual_zh.md
