### ISSUE TITLE
希望在Tensor中添加配置SetScalar接口，来配置vsi_nn_tensor_t的scalar属性

### ISSUE THREAD

**Issue by xie-oritek** [VeriSilicon/TIM-VX#641]
因为在Gather算子的op_setup接口中，会根据是否为Scalar值，来计算输出的维度信息，如下：

https://github.com/VeriSilicon/TIM-VX/blob/265e74ff1668d21214c67c360c0bef91c44ca7fb/src/tim/vx/internal/src/ops/vsi_nn_op_gather.c#L196-L197

**Comment by sunshinemyson** [comment]
@xie-oritek ，

可以的。我们放在10月把他enable起来。

**Comment by sunshinemyson** [comment]
Postpone to end of Nov.

**Comment by sunshinemyson** [comment]
https://github.com/VeriSilicon/TIM-VX/pull/655
