### ISSUE TITLE
双向LSTM算子内部创建的Tensor对量化参数处理有问题

### ISSUE THREAD

**Issue by xie-oritek** [VeriSilicon/TIM-VX#647]
https://github.com/VeriSilicon/TIM-VX/blob/61ea0091ca8e8a84d408e728269de4a449882fa7/src/tim/vx/ops/bidirectional_sequence_lstm.cc#L157-L158

当输入输出的Tensor有量化参数时，需要同步将量化参数拷贝到第一个reverse的输出和第二个reverse的输入

**Comment by sunshinemyson** [comment]
@xie-oritek ，

你没有测试用例呢？我们好分析验证。谢谢

**Comment by xie-oritek** [comment]
[lstm_allinput_bi.zip](https://github.com/VeriSilicon/TIM-VX/files/12603997/lstm_allinput_bi.zip)
上面是使用trace功能导出的用例

**Comment by sunshinemyson** [comment]
@xie-oritek ,
https://github.com/VeriSilicon/tflite-vx-delegate/blob/main/op_map.cc#L2392 之处的数据格式可以参考这里的实现。
