### ISSUE TITLE
Any plan to add quantized attention?

### ISSUE THREAD

**Issue by fengyuentau** [VeriSilicon/TIM-VX#654]
Hello guys, thanks for the great work! I wonder if you have any plan to support quantized attention?

**Comment by chenfeiyue-cfy** [comment]
Hi, could you please give more information ? For example, what do you mean by "quantized attention"？Is it simply refers to quantizing all data types or other practices such as specific op quantization(e.g. softmax)?

**Comment by fengyuentau** [comment]
Something like this: https://github.com/microsoft/onnxruntime/blob/main/docs/ContribOperators.md#com.microsoft.QAttention. Operator prototype may vary though.

**Comment by chenfeiyue-cfy** [comment]
Thank you for your interest, unfortunately we have no plans to support this project yet.

**Comment by fengyuentau** [comment]
Ok, thanks for the response. One more question is any ongoing plan about attention?

**Comment by chenfeiyue-cfy** [comment]
It will depends on HW support.Which board (IP) are you currently using?

**Comment by fengyuentau** [comment]
> Which board (IP) are you currently using?
Khadas VIM3 with A311D SoC.

**Comment by chenfeiyue-cfy** [comment]
> > Which board (IP) are you currently using?
> 
> Khadas VIM3 with A311D SoC.
This hardware can provide functional support but cannot guarantee good performance such as accuracy and efficiency of GEMM operations in attention models.

**Comment by fengyuentau** [comment]
Okay, thank you for your patience and all the helpful information.
