### ISSUE TITLE
What does the producer and consumer mean?

### ISSUE THREAD

**Issue by engineer1109** [VeriSilicon/TIM-VX#693]
I found the graph interface has producer and consumer two means.
What mean?

And function:
```
UpdateTensorConsumersMap
RenewTensorConsumersMap
UpdateTensorProducerMap
GetConsumersOp
GetProducerOp
```
means what

**Comment by chenfeiyue-cfy** [comment]
Hi, these map structures are desined to facilitate obtaining the entire topology of the graph from any location. The TensorProducerMap and TensorConsumerOp are both <tensor, op> type maps, where the former stores the successor operators for the current tensor, and the latter stores the predecessor operators for the current tensor.
As for functions, the Update*** functions are called when initializing the structure of the entire graph, meaning that every time UpdateMap is called, a new binding information between tensor and operation is added to the related map. RenewTensorConsumersMap is used to handle some const tensor  that are not supported by the definitions of operations in lower-level software. We convert the initialized timvx tensor into a new tensor through data conversion and other means, hence we need to modify the map. The Get*** function returns the smart pointer of the Consumer/Producer Operation for the current tensor.

**Comment by engineer1109** [comment]
Thanks for your answer
