### ISSUE TITLE
VeriSilicon VIP-Lite SDK

### ISSUE THREAD

**Issue by RHeCi** [VeriSilicon/TIM-VX#696]
We want to accelerate our AI with the VIP8000Nano NPU. Since we have a proprietary operating system, we cannot use the binaries from yocto layers.

Can you provide us with the "VeriSilicon VIP-Lite SDK" or "VeriSilicon OpenVX SDK" so that we can port tim-vx to our platform?

**Comment by sunshinemyson** [comment]
Please contact sales team. RD team is not the correct person for new release request for driver.
